FROM golang:1.24-alpine
RUN apk add --no-cache \
    libwebp-dev \
    build-base
WORKDIR /app
RUN go install github.com/air-verse/air@latest
COPY go.* ./
RUN go mod download
CMD ["air", "-c", ".air.toml"]